index:
  number_of_shards: 5
  mapping:
    nested_fields:
      limit: 200
  #    query:
  #        default_field: text
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/similarity.html
  similarity:
    my_bm25:
      type: BM25
      b: 0.236

  analysis:
    filter:
      # english analyzer, see http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.4/analysis-lang-analyzer.html#english-analyzer
      english_stop:
        type: stop
        stopwords_path: analysis/english_stop.txt
      english_keywords:
        type: keyword_marker
        keywords:
          - Allah
          - God
          - Moses
          - Musa
          - Isa
          - Jesus
          - Noah
      arabic_keywords:
        type: keyword_marker
        keywords:
          - ياسين
          - موسي
          - عيسي
          - يوسف
          - ابراهيم
          - اسماعيل
          - نوح
      english_stemmer:
        type: stemmer
        language: english
      english_possessive_stemmer:
        type: stemmer
        language: possessive_english
      autocomplete:
        type: "edge_ngram"
        min_gram: 1
        max_gram: 30

      unique_tokens:
        type: unique
        only_on_same_position: true
      arabic_ngram:
        type: ngram
        min_gram: 5
        max_gram: 6
      arabic_stop:
        type: stop
        stopwords: _arabic_
      arabic_stemmer:
        type: stemmer
        language: arabic
      quran_arabic_word_synonym:
        type: synonym
        expand: true
        synonyms_path: analysis/quran_word_synonym.txt
      noun_synonym:
        type: synonym
        expand: true
        synonyms_path: analysis/noun_synonym.txt
      shingle_filter:
        type: shingle
        min_shingle_size: 2
        max_shingle_size: 2
        output_unigrams: false

    analyzer:
      autocomplete_arabic:
        type: custom
        tokenizer: whitespace
        filter:
          - arabic_normalization
          - autocomplete
          - arabic_keywords
      arabic_synonym_normalized:
        tokenizer: icu_tokenizer
        filter:
          - arabic_keywords
          - quran_arabic_word_synonym
          - arabic_normalization
          - arabic_stemmer
          - arabic_stop
          - icu_folding
          - noun_synonym

      arabic_normalized:
        tokenizer: whitespace
        filter:
          - arabic_normalization
          - arabic_keywords
      arabic_stemmed:
        tokenizer: whitespace
        filter:
          - arabic_normalization
          - arabic_stemmer
          - arabic_keywords
      arabic_ngram:
        tokenizer: whitespace
        filter:
          - arabic_normalization
          - arabic_ngram
          - reverse
          - unique_tokens
          - arabic_keywords
      english:
        tokenizer: standard
        filter:
          - english_possessive_stemmer
          - lowercase
          - english_stop
          - english_keywords
          - english_stemmer
          - noun_synonym
          - asciifolding
      arabic:
        tokenizer: whitespace
        filter:
          - arabic_normalization
          - arabic_stemmer
          - arabic_keywords
      minimal:
        tokenizer: whitespace
        filter:
          - lowercase
      shingle_analyzer:
        type: custom
        tokenizer: standard
        filter:
          - lowercase
          - shingle_filter
